export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const GET_CURRENT_LOCATION_FAILURE = "GET_CURRENT_LOCATION_FAILURE";
export const RECEIVE_CURRENT_LOCATION = "RECEIVE_CURRENT_LOCATION";
